project06/depot/config/routes.rb
Depot::Application.routes.draw do
  resources :users

  resources :games

  get "games/index"

  root :to => 'games#index', :as => 'games'

end

project06/depot/app/models/game.rb
class Game < ActiveRecord::Base
	validates :title, :presence => true
end

project06/depot/app/models/user.rb
class User < ActiveRecord::Base
	validates :name, :presence => true, :uniqueness => true
	validates :password, :confirmation => true
	attr_accessor :password_confirmation
	attr_reader :password
	validate :password_must_be_present

	private
		def password_must_be_present
			errors.add(:password, "Missing password") unless hashed_password.present?
		end
end

def User.encrypt_password(password, salt)
	Digest::SHA2.hexdigest(password + "wibble" + salt)
end

def generate_salt
	self.salt = self.object_id.to_s + rand.to_s
end

project06/depot/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

project06/depot/app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
	@games = Game.paginate :page=>params[:page], :game=>'created_at desc', :per_page => 6

	respond_to do |format|
		format.html # index.html.erb
		format.xml { render :xml => @orders }
	end
  end
end

project06/depot/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

project06/depot/app/helpers/application_helper.rb
module ApplicationHelper
end

project06/depot/app/helpers/games_helper.rb
module GamesHelper
end

project06/depot/app/helpers/users_helper.rb
module UsersHelper
end

project06/depot/app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :rating %>
	<br><%= radio_button_tag ':rating', 'Amazing' %> Amazing
    	<br><%= radio_button_tag ':rating', 'Good' %> Good
    	<br><%= radio_button_tag ':rating', 'Meh' %> Meh
    	<br><%= radio_button_tag ':rating', 'Horrible' %> Horrible
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project06/depot/app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

project06/depot/app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Rating</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr style="<%= cycle('background:#ccc;', 'background:#fff;') %>">
    <td><%= game.title %></td>
    <td><%= game.rating %></td>
    <td><%= game.date %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<p><%= will_paginate @games %></p>
<br />

<%= link_to 'New Game', new_game_path %>

project06/depot/app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

project06/depot/app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b> title:</b>
  <%= @game. title %>
</p>

<p>
  <b>Rating:</b>
  <%= @game.rating %>
</p>

<p>
  <b>Date:</b>
  <%= @game.date %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

project06/depot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gamez</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

project06/depot/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label : name %><br />
    <%= f.text_field : name %>
  </div>
  <div class="field">
    <%= f.label :hashed_password %><br />
    <%= f.text_field :hashed_password %>
  </div>
  <div class="field">
    <%= f.label :salt %><br />
    <%= f.text_field :salt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project06/depot/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

project06/depot/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th> name</th>
    <th>Hashed password</th>
    <th>Salt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user. name %></td>
    <td><%= user.hashed_password %></td>
    <td><%= user.salt %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

project06/depot/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

project06/depot/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b> name:</b>
  <%= @user. name %>
</p>

<p>
  <b>Hashed password:</b>
  <%= @user.hashed_password %>
</p>

<p>
  <b>Salt:</b>
  <%= @user.salt %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>