project05/project04/config/routes.rb
Articles::Application.routes.draw do
  get "authors/index"

  resources :articles

   root :to => 'articles#index'

end

project05/project04/app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, :author, :body, :presence => true
	validate :author_is_not_pat

	private
		def author_is_not_pat
			errors.add(:author, "Pat cannot post articles!") if author.downcase.include? "pat"
		end
end

project05/project04/app/models/author.rb
class Article < ActiveRecord::Base
	has_attached_file :photo,
		:url  => "/assets/products/:id/:style/:basename.:extension",
		:path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"
	validates_attachment_presence :photo
	validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

project05/project04/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate :page=>params[:page], :order=>'created_at desc', :per_page => 10

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, :notice => 'Article was successfully created.' }
        format.json { render :json => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, :notice => 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

project05/project04/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
	@authors = Authors.all
  end
end

project05/project04/app/helpers/articles_helper.rb
module ArticlesHelper
	def authorNames
		[
			['Name1']
		]
	end
end

project05/project04/app/helpers/authors_helper.rb
module AuthorsHelper
end

project05/project04/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= select_tag :author, authorNames %> 
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project05/project04/app/views/articles/edit.html.erb
<% content_for :subtitle do %>
	... my cousin works for Bit.ly
<% end %>

<%= link_to (articles_path) do %> <%= image_tag "icons/arrow_left.png" %><span id="tt">Back to Articles</span> <% end %>

<h2>Editing "<%= @article. title %>"</h2>

<%= render 'form' %>

project05/project04/app/views/articles/index.html.erb
<% content_for :subtitle do %>
	... with a name .com hipsters love!
<% end %>

<h2>All the World's Articles<span><%= link_to (new_article_path) do %> <%= image_tag "icons/new.png" %><span id="tt">New Article</span> <% end %></span></h2>

<table>
	<tr style="background:#999;">
		<td style="border:1px solid #000;color:#fff;width:100px;">Title</td>
		<td style="border:1px solid #000;color:#fff;width:100px;">Author</td>
		<td style="border:1px solid #000;color:#fff;width:300px;">Body</td>
		<td style="border:1px solid #000;color:#fff;width:100px;">Date</td>
		<td></td>
	</tr>
	
<% @articles.each do |article| %>
	<tr style="background:<%= cycle('#CCC', '#FFF') %>">
        	<td style="border:1px solid #000;width:100px;overflow:hidden;"><%= article.title %></td>
        	<td style="border:1px solid #000;width:100px;overflow:hidden;"><%= article.author %></td>
        	<td style="border:1px solid #000;width:100px;overflow:hidden;"><%= article.body %></td>
       		<td style="border:1px solid #000;width:100px;overflow:hidden;"><%= article.created_at.strftime("%a. %b. %d, %Y") %></td>
        	<td width="20"><%= link_to (article) do %> <%= image_tag "icons/magnifier.png" %><span id="tt">View</span> <% end %></td>
        	<td width="20"><%= link_to (edit_article_path(article)) do %> <%= image_tag "icons/note_edit.png" %><span id="tt">Edit</span> <% end %></td>
        	<td width="20"><%= link_to (article, :confirm => 'Are you sure?', :method => :delete) do %> <%= image_tag "icons/delete.png" %><span id="tt">Delete</span> <% end %></td>
    	</tr>
<% end %>

</table>

<br /><img src="icons/application_view_list.png" /> <%= pluralize(@articles.count, "article") %><br /><br />
<%= will_paginate @articles %>

project05/project04/app/views/articles/new.html.erb
<% content_for :subtitle do %>
	... not just for the country of Spain
<% end %>

<%= link_to (articles_path) do %> <%= image_tag "icons/arrow_left.png" %><span id="tt">Back to Articles</span> <% end %>

<h2>Creating a New Article</h2>

<%= render 'form' %>

project05/project04/app/views/articles/show.html.erb
<% content_for :subtitle do %>
	... what's "Articl" in Spanish anyway?
<% end %>

<p id="notice"><%= notice %></p>
<%= link_to (articles_path) do %> <%= image_tag "icons/arrow_left.png" %><span id="tt">Back to Articles</span> <% end %>
<%= link_to (edit_article_path(@article)) do %> <%= image_tag "icons/note_edit.png" %><span id="tt">Edit</span> <% end %>
<%= link_to (@article, :confirm => 'Are you sure?', :method => :delete) do %> <%= image_tag "icons/delete.png" %><span id="tt">Delete</span> <% end %>


<h2><%= @article. title %></h2>

by <%= @article.author %>, <%= @article.created_at.strftime("%b. %d, %Y") %>

<p>
  <%= @article.body %>
</p>

project05/project04/app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @ author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @ author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %> 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project05/project04/app/views/authors/edit.html.erb
<%= link_to (author_path) do %> <%= image_tag "icons/arrow_left.png" %><span id="tt">Back to Author</span> <% end %>

<h2>Editing "<%= @author. title %>"</h2>

<%= render 'form' %>

project05/project04/app/views/authors/index.html.erb
<h1>Authors Admin</h1>

<% @authors.each do |author| %>
<div class="entry">
	<%= image_tag(author.image_url) %>
	<%= author.name %>
</div>

project05/project04/app/views/authors/new.html.erb
<%= link_to (author_path) do %> <%= image_tag "icons/arrow_left.png" %><span id="tt">Back to Author</span> <% end %>

<h2>Creating a New Author</h2>

<%= render 'form' %>

project05/project04/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to (authors_path) do %> <%= image_tag "icons/arrow_left.png" %><span id="tt">Back to Authors</span> <% end %>
<%= link_to (edit_author_path(@author)) do %> <%= image_tag "icons/note_edit.png" %><span id="tt">Edit</span> <% end %>
<%= link_to (@author, :confirm => 'Are you sure?', :method => :delete) do %> <%= image_tag "icons/delete.png" %><span id="tt">Delete</span> <% end %>


<h2><%= @author. name %></h2>

<%= image_tag @author.photo.url() %>

project05/project04/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Articl.es -- All the World's Articles (with a name .com hipsters love)</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Articl.es<br /><span><%= yield :subtitle %></span></h1>

<%= yield %>

</body>
</html>